// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqkhjxnjetvhmmwrwojo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxa2hqeG5qZXR2aG1td3J3b2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjg3NDIsImV4cCI6MjA2NzkwNDc0Mn0.0Dzg1D3qRl3WIN5Xb-rcR80b5Id1qPmwSR3hDtXzg1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});